title: Matt McManus
author: Matt McManus
url: http://www.mcmanus.io
permalink: /:title
paginate: 10
paginate_path: "blog/page:num"

sass:
  sass_dir: _scss
  style: :compressed

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
