title: Matt McManus
author: Matt McManus
pygments: true

permalink: /:title
paginate: 10
paginate_path: "blog/page:num"

markdown: kramdown
kramdown:
  input: GFM

gems:
- jekyll-redirect-from


prose:
  rooturl: '_posts'
  siteurl: 'http://www.mcmanus.io'
  media: 'images'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
